language: node_js
node_js:
- "stable"
after_success:
- npm run coveralls
notifications:
  slack: 1593561702extramural:GwaO5sOja7Oy2kdfJ8xe1jTh
addons:
  sauce_connect:
    username: "sumnerfit"
    access_key: "jg_4SsRbb"